#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-rngWELL
Version  : 0.10.10
Release  : 47
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/rngWELL_0.10-10.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/rngWELL_0.10-10.tar.gz
Summary  : Toolbox for WELL Random Number Generators
Group    : Development/Tools
License  : BSD-3-Clause
Requires: R-rngWELL-lib = %{version}-%{release}
BuildRequires : R
BuildRequires : buildreq-R

%description
which were introduced in Panneton et al. (2006), ``Improved Long-Period

%package lib
Summary: lib components for the R-rngWELL package.
Group: Libraries

%description lib
lib components for the R-rngWELL package.


%prep
%setup -q -n rngWELL
pushd ..
cp -a rngWELL buildavx2
popd
pushd ..
cp -a rngWELL buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731650159

%install
export SOURCE_DATE_EPOCH=1731650159
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rngWELL/CITATION
/usr/lib64/R/library/rngWELL/DESCRIPTION
/usr/lib64/R/library/rngWELL/INDEX
/usr/lib64/R/library/rngWELL/LICENSE
/usr/lib64/R/library/rngWELL/Meta/Rd.rds
/usr/lib64/R/library/rngWELL/Meta/features.rds
/usr/lib64/R/library/rngWELL/Meta/hsearch.rds
/usr/lib64/R/library/rngWELL/Meta/links.rds
/usr/lib64/R/library/rngWELL/Meta/nsInfo.rds
/usr/lib64/R/library/rngWELL/Meta/package.rds
/usr/lib64/R/library/rngWELL/NAMESPACE
/usr/lib64/R/library/rngWELL/NEWS
/usr/lib64/R/library/rngWELL/R/rngWELL
/usr/lib64/R/library/rngWELL/R/rngWELL.rdb
/usr/lib64/R/library/rngWELL/R/rngWELL.rdx
/usr/lib64/R/library/rngWELL/help/AnIndex
/usr/lib64/R/library/rngWELL/help/aliases.rds
/usr/lib64/R/library/rngWELL/help/paths.rds
/usr/lib64/R/library/rngWELL/help/rngWELL.rdb
/usr/lib64/R/library/rngWELL/help/rngWELL.rdx
/usr/lib64/R/library/rngWELL/html/00Index.html
/usr/lib64/R/library/rngWELL/html/R.css
/usr/lib64/R/library/rngWELL/tests/test-well.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/rngWELL/libs/rngWELL.so
/V4/usr/lib64/R/library/rngWELL/libs/rngWELL.so
/usr/lib64/R/library/rngWELL/libs/rngWELL.so
